version: '3.7'

services:
    2017-latest:
        image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
        ports:  
          - "15597:1433"
        environment:
          SA_PASSWORD: "Password0!"
          ACCEPT_EULA: "Y"
        volumes: 
          - C:\MSSQL\BACKUP\KEEP:/var/opt/mssql/backups
          - C:\MSSQL\DockerFiles\ForUpgrade\system:/var/opt/mssql/data
          - C:\MSSQL\DockerFiles\ForUpgrade\datafiles:/var/opt/sqlserver