version: '3.7'

services:
    dbatoolssql1:
        image: dbatools/sqlinstance
        ports:  
          - "15591:1433"
          - "5022:5022"
        volumes: 
          - /home/rob/Documents/docker/volumes/dbatools:/var/opt/mssql/backups
    dbatoolssql2:
        image: dbatools/sqlinstance2
        ports:  
          - "15592:1433"
          - "5023:5023"
        volumes: 
          - /home/rob/Documents/docker/volumes/dbatools:/var/opt/mssql/backups
